### ISSUE TITLE
v0.8 not building due to pointy lib. 

### ISSUE THREAD

**Issue by zdannar** [DougLau/mvt#4]
Doug,

Maybe there isn't a dependency that is updated.  I am running into issues with 0.8 due to pointy issues.  The x, y values in pointy are private.  If you change to the methods, it looks good until you try compiling pointy.  I can provide details, but it may be easiest to just compile mvt.

Thanks.

**Comment by DougLau** [comment]
That's what I get for using local patches.  0.8.0 is yanked, try 0.8.1

**Comment by zdannar** [comment]
Doug,

I pulled down 0.8.1 this morning and things look good.  

Thank you.
